http:
  port: "8081"
  
anypoint:
  api:
    id: "20236336"
  businessGroup: "ae6d7954-6fc2-4f3e-8777-80ff8aabd859"
  portal:
    assetId: anypoint-race-api
    version: "3.2.6"
    timeout: "20000"
    
referee:
  host: referee-papi
  port: "8081"
  protocol: HTTP
  path: /api

racedata:
  host: race-data-sapi
  port: "8081"
  protocol: HTTP
  path: /api
      